### ISSUE TITLE
第7世代のポケモン追加

### ISSUE THREAD

**Issue by loose-art** [togoshiorg/togoshi-bot#14]
第7世代のポケモンを追加したい。

**Comment by usagi-f** [comment]
一番対応したいけれど、ドット絵の画像がないためどうしよう…という状態ナウ

**Comment by usagi-f** [comment]
pokeapiの開発リポジトリに `Generation 7 updates` というProjectが立てられていました。
https://github.com/PokeAPI/pokeapi/projects/1

（ただし１つも進んでいない）

**Comment by loose-art** [comment]
そろそろ追加されるっぽい
https://github.com/PokeAPI/pokeapi/pull/305

**Comment by usagi-f** [comment]
Good newsです。
pokeapiのPR #305 がMergeされています。

**Comment by usagi-f** [comment]
### 提案
第７世代ポケモンのデータも返却されるようになったことで提案。

pokeapiは画像データも `sprites.front_default` にパスとして格納されています。
そして現在利用しているpokestadium.comでは未だ第６世代までのspriteしかありません。

そこで、コードも綺麗にできそうですしpokeapiからの画像パスをそのまま使いませんか？

### 懸念
ただし、以下のように静止画になってしまいます。
https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/750.png

**Comment by usagi-f** [comment]
- pkparaiso : 色違いが無い
- pokemonshowdown : リスクあり？
- pokeapi : PRの必要あり

**Comment by usagi-f** [comment]
pkparaisoに色違いがありました。
`animados` に `-shiny` を付与することでアクセス可能です。

https://www.pkparaiso.com/imagenes/xy/sprites/animados/bulbasaur.gif
https://www.pkparaiso.com/imagenes/xy/sprites/animados-shiny/bulbasaur.gif

https://www.pkparaiso.com/imagenes/sol-luna/sprites/animados/lunala.gif
https://www.pkparaiso.com/imagenes/sol-luna/sprites/animados-shiny/lunala.gif
